// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SmartInventoryApp.Entity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace SmartInventoryApp.SmartInventoryContext
{
    public partial interface ISmartInventoryDBContextProcedures
    {
        Task<int> AddNewSaleAsync(int? ProductID, int? Quantity, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetLowStockProductsResult>> GetLowStockProductsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
