// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SmartInventoryApp.Entity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace SmartInventoryApp.SmartInventoryContext
{
    public partial class SmartInventoryDBContext
    {
        private ISmartInventoryDBContextProcedures _procedures;

        public virtual ISmartInventoryDBContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new SmartInventoryDBContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ISmartInventoryDBContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class SmartInventoryDBContextProcedures : ISmartInventoryDBContextProcedures
    {
        private readonly SmartInventoryDBContext _context;

        public SmartInventoryDBContextProcedures(SmartInventoryDBContext context)
        {
            _context = context;
        }

        public virtual async Task<int> AddNewSaleAsync(int? ProductID, int? Quantity, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ProductID",
                    Value = ProductID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Quantity",
                    Value = Quantity ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[AddNewSale] @ProductID = @ProductID, @Quantity = @Quantity", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<GetLowStockProductsResult>> GetLowStockProductsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetLowStockProductsResult>("EXEC @returnValue = [dbo].[GetLowStockProducts]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
