// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmartInventoryApp.Entity
{
    public partial class GetLowStockProductsResult
    {
        public int ProductID { get; set; }
        [StringLength(100)]
        public string ProductName { get; set; }
        public int Stock { get; set; }
    }
}
