// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartInventoryApp.Entity;

public partial class Purchase
{
    [Key]
    public int PurchaseID { get; set; }

    public int ProductID { get; set; }

    public int SupplierID { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal TotalCost { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PurchaseDate { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("Purchases")]
    public virtual Product Product { get; set; }

    [ForeignKey("SupplierID")]
    [InverseProperty("Purchases")]
    public virtual Supplier Supplier { get; set; }
}