// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartInventoryApp.Entity;

public partial class Supplier
{
    [Key]
    public int SupplierID { get; set; }

    [Required]
    [StringLength(100)]
    public string SupplierName { get; set; }

    [StringLength(15)]
    public string ContactNumber { get; set; }

    [StringLength(200)]
    public string Address { get; set; }

    [InverseProperty("Supplier")]
    public virtual ICollection<Purchase> Purchases { get; set; } = new List<Purchase>();
}